### ISSUE TITLE
Unable to Access Hookup Guide

### ISSUE THREAD

**Issue by flagrantshores** [sparkfunX/Qwiic_Power_Meter-ACS37800#1]
Love the work, just unable to access the hookup guide which would be very helpful.

**Comment by PaulZC** [comment]
Hi @Atuttl ,
Thanks for the feedback!
We're still working on the hook-up guide, but I have added a **draft** guide [here](https://github.com/sparkfunX/Qwiic_Power_Meter-ACS37800/blob/master/HOOKUP.md). Please excuse the hand-drawn diagrams.
Best wishes,
Paul
